function hasNeverAutologin(b,a){var d=lpcanonizeUrl(b);if(g_neverurls.onlyautologins&&0<g_neverurls.onlyautologins.length){for(var f=!1,c=0;g_neverurls.onlyautologins&&c<g_neverurls.onlyautologins.length;c++){var e=g_neverurls.onlyautologins[c];if(e==a||e==d){f=!0;break}}if(!f)return!0}for(c=0;g_neverurls.neverautologins&&c<g_neverurls.neverautologins.length;c++)if(e=g_neverurls.neverautologins[c],e==a||e==d)return!0;return!1}
function hasNeverGenerate(b,a){var d=lpcanonizeUrl(b);if(g_neverurls.onlygenerates&&0<g_neverurls.onlygenerates.length){for(var f=!1,c=0;g_neverurls.onlygenerates&&c<g_neverurls.onlygenerates.length;c++){var e=g_neverurls.onlygenerates[c];if(e==a||e==d){f=!0;break}}if(!f)return!0}for(c=0;g_neverurls.nevergenerates&&c<g_neverurls.nevergenerates.length;c++)if(e=g_neverurls.nevergenerates[c],e==a||e==d)return!0;return!1}
function hasNeverFormFill(b,a){var d=lpcanonizeUrl(b);if(g_neverurls.onlyformfills&&0<g_neverurls.onlyformfills.length){for(var f=!1,c=0;g_neverurls.onlyformfills&&c<g_neverurls.onlyformfills.length;c++){var e=g_neverurls.onlyformfills[c];if(e==a||e==d){f=!0;break}}if(!f)return!0}for(c=0;g_neverurls.neverformfills&&c<g_neverurls.neverformfills.length;c++)if(e=g_neverurls.neverformfills[c],e==a||e==d)return!0;return!1}var g_accessibility_enabled=-1;
function handleFill(b,a){var d=!1;if(lploggedin&&null==grid_getdata("active")||skiplogin())if("autofillaid"==a.cmd||"autologinaid"==a.cmd){var f=a.aid;g_last_launch[f]=(new Date).getTime();if("undefined"!=typeof g_sites[f]){var d="autologinaid"==a.cmd,c=!0,e=g_sites[f];a.no_manualfill_on_saveall&&e.save_all&&(c=!1);fill(b,g_sites[f],null,d,!d,"all",!0,!1,c)}}else if(!("undefined"==typeof a||!a||"undefined"==typeof a.url))if(c=a.url,e=lp_gettld_url(c),!lp_url_is_lastpass(c)){if("undefined"!=typeof g_launches[b]&&
g_launches[b]&&(f=g_launches[b],check_ident_aid(f)&&compare_tlds(e,lp_gettld_url(g_sites[f].url)))){if("undefined"!=typeof a.numpass&&0<a.numpass||""==g_sites[f].password)g_launches[b]=null;"undefined"!=typeof g_sites[f]&&(is_guiless()?fill(b,g_sites[f],null,!1,!1,"all",!0,!1,!1,!1):fill(b,g_sites[f],null,!0,!1,a.docnum,!1,!0),g_launches[b]=null)}var g=getsites(e),g=reorderOnURL(g,c,!0);hasNeverAutologin(c,e)&&(g=[]);e=0==a.force&&a.topurl!=c?lp_gettld_url(a.topurl):"";""!=e&&hasNeverAutologin(a.topurl,
e)&&(g=[]);for(var j in g){try{if(islastpass&&g_ischrome&&1==g[j].basic_auth&&0>=g_accessibility_enabled&&0==lpGetPref("basicauthnever",0))if(g_is_mac&&have_binary_function("accessibility_enabled"))call_binary_function("accessibility_enabled",function(a){g_accessibility_enabled=a?1:0;0==g_accessibility_enabled&&setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:0,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to enable access for assistive devices.")})})},
100)});else if((g_is_win||g_is_mac)&&!have_binary())g_accessibility_enabled=0,setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:1,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to install the binary version of LastPass for Chrome.")})})},100)}catch(k){}var h=!1,f=g[j].aid;if(check_ident_aid(f)&&"undefined"!=typeof g_sites[f]){e=g_sites[f];e.never_autofill&&(h=!0);if(e.pwprotect||g_prompts.login_site_prompt)h=
!0;if(!e.genpw&&!(0==e.fields.length&&""==e.username)){0==e.url.indexOf("https://")&&0!=c.indexOf("https://")&&(h=!0);0==parseInt(lpGetPref("automaticallyFill",1))&&0==parseInt(lpGetPref("highlightFields",1))&&(h=!0);if(!h){if(f=!e.save_all)"undefined"==typeof g_fillfieldsmatches[c]&&(g_fillfieldsmatches[c]=[]),g_fillfieldsmatches[c][g_fillfieldsmatches[c].length]=e,g_fillfieldsmatchescurridx[c]=0;j=parseInt(lpGetPref("automaticallyFill",1));fill(b,e,a.docid,null,f,a.docnum,null,!0,null,j)}0!=lpGetPref("showFillNotificationBar",
1)&&(get_selected_tab(null,function(){sendCS(b,{cmd:"showfillnotification",text:gs("LastPass has filled your login information into the form on this page."),sites:cache_usernames(g),docnum:a.docnum})}),d=!0);break}}}!d&&0==lpGetPref("showNotificationsAfterClick",1)&&checkgenpwfillforms(b,c)}}
function checkWeakAndDuplicate(b,a,d){if(g_showweakdupalerts&&qualifyForWeakCheck(getpasswordfromacct(b))&&(g_ischrome||g_issafari))!1==g_disablepwalerts&&("undefined"==typeof b.noalert||"1"!=b.noalert)&&getWeakAndDuplicateIds(g_username_hash,g_username,function(f){isDuplicateSite(f[0],b.aid)?(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:b.aid,name:b.name,username:getusernamefromacct(b),alerttype:"duplicate",tld:d,tabid:a},set_badge(g_notification_data,a),drawIconAtRotation(0)):
isWeakPassword(f[1],b.aid)&&(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:b.aid,name:b.name,username:getusernamefromacct(b),alerttype:"weak",tld:d,tabid:a},set_badge(g_notification_data,a),drawIconAtRotation(0))})}
function checkgenpwfillforms(b,a){var d=lp_gettld_url(a),f=1!=lpGetPref("showGenerateNotifications",1)||hasNeverGenerate(a,d),c=1!=lpGetPref("showFormFillNotifications",1)||hasNeverFormFill(a,d),e=[];if(do_experimental_popupfill){for(var g=0;g<g_formfills.length;g++)check_ident_ffid(g_formfills[g].ffid)&&(e[e.length]=g_formfills[g]);0==e.length&&(c=!0);sendCS(b,{cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:c,sites:cache_usernames(reorderOnURL(getsites(d),a,!0,!0)),formfills:LPJSON.stringify(e),
ff:g_cachedffdat,active:g_popupfill_last_active[b],activefieldid:g_popupfill_last_active_fieldid[b]},"all")}else{if(!c){for(g=0;g<g_formfills.length;g++)check_ident_ffid(g_formfills[g].ffid)&&(e[e.length]=g_formfills[g]);0==e.length&&(c=!0)}(!f||!c)&&sendCS(b,{cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:c,sites:cache_usernames(reorderOnURL(getsites(d),a,!0,!0)),formfills:LPJSON.stringify(e),ff:g_cachedffdat},"all")}}
function cache_usernames(b){for(var a in b)b[a].useusername=getusernamefromacct(b[a]);return LPJSON.stringify(b)}
function hasNeverSave(b,a){var d=lpcanonizeUrl(b);if(g_neverurls.onlyaccounts&&0<g_neverurls.onlyaccounts.length){for(var f=!1,c=0;g_neverurls.onlyaccounts&&c<g_neverurls.onlyaccounts.length;c++){var e=g_neverurls.onlyaccounts[c];if(e==a||e==d){f=!0;break}}if(!f)return!0}for(c=0;g_neverurls.neveraccounts&&c<g_neverurls.neveraccounts.length;c++)if(e=g_neverurls.neveraccounts[c],e==a||e==d)return!0;return!1}
function handleNever(b,a){if("neverautofill"==a.cmd){var d=a.aid;if("undefined"==typeof g_sites[d])return;g_sites[d].never_autofill=!0;g_sites[d].autologin=!1;d="aid="+en(d);lpMakeRequest(base_url+"set_never_autofill.php",d,null,null)}else if("neverdomain"==a.cmd||"neverpage"==a.cmd){var f="neverdomain"==a.cmd?lp_gettld_url(a.url):lpcanonizeUrl(a.url),d="url="+en(AES.url2hex(f));"undefined"!=typeof a.fromsave&&a.fromsave?g_neverurls.neveraccounts.push(f):"undefined"!=typeof a.fromgenerate&&a.fromgenerate?
(d+="&type=1",g_neverurls.nevergenerates.push(f)):"undefined"!=typeof a.fromformfill&&a.fromformfill?(d+="&type=2",g_neverurls.neverformfills.push(f)):"undefined"!=typeof a.fromshowicons&&a.fromshowicons?(d+="&type=6",g_neverurls.nevershowicons.push(f)):(d+="&type=3",g_neverurls.neverautologins.push(f));lpMakeRequest(base_url+"add_never.php",d,null,null)}g_local_accts_version++;rewritelocalfile()}
function handleSave(b,a){if(!("undefined"==typeof SAVEALLFORMSUBMITS&&(!lploggedin||lp_url_is_lastpass(a.url)))){for(var d=a.formdata.split("\n"),f=!1,c=!1,e="",g="",j=[],k=0;k<d.length;k++){var h=d[k],h=h.split("\t");if(!(4!=h.length&&5!=h.length)){var p=decodeURIComponent(h[2]),l=h[3];if((!f||!c)&&("text"==l||"email"==l||"tel"==l||"url"==l)&&p.length)e=p,f=!0,!1==c&&"undefined"!=typeof SpecialSites[lpcanonizeUrl(a.url)]&&(c=!0);"password"==l&&(j[j.length]=p,!c&&p.length&&(g=p,c=!0))}}if(c){a.username=
e;a.password=g;!f&&1<j.length&&j[0]!=j[1]&&(a.username=j[0],a.password=j[1]);c=lp_gettld_url(a.url);a.tld=c;var p=!1,r="";1<j.length&&j[j.length-1]==j[j.length-2]&&""!=j[j.length-1]?(p=!0,r=j[j.length-1]):1<j.length&&(j[0]==j[1]&&""!=j[0])&&(p=!0,r=j[0]);var m=[];if(p&&(m=getsites(c,!0),a.createacct=2==j.length||0<array_length(m),a.createacct)){for(var s=j="",u="",n="",k=0;k<d.length;k++)if(h=d[k],h=h.split("\t"),!(4!=h.length&&5!=h.length)){l=h[3];if(""==j&&("email"==l||"tel"==l||"text"==l||"url"==
l)&&""!=h[1]&&""!=h[2]){var t=decodeURIComponent(h[1]),q=get_ff_translation("ff_username_regexp");""!=q&&(q=RegExp(q,"i"),q.exec(t)&&(j=t,s=decodeURIComponent(h[2])))}if(""==u&&("email"==l||"tel"==l||"text"==l||"url"==l)&&""!=h[1]&&""!=h[2])t=decodeURIComponent(h[1]),l=get_ff_translation("ff_email_regexp"),""!=l&&(q=RegExp(l,"i"),q.exec(t)&&(u=t,n=decodeURIComponent(h[2])));if(""!=j&&""!=u)break}""==j&&(j=u,s=n);a.username_field=j;""!=s&&(a.username=s)}if(p&&0<array_length(m)){if(!("undefined"!=typeof g_didchangepw[SHA256(r+
c)]&&g_didchangepw[SHA256(r+c)]>(new Date).getTime()-6E5)&&(g_notification_type="change",a.newpw=r,g_notification_data=a,sendTS({cmd:"notification",type:"change"}),0!=lpGetPref("showChangeNotificationBar",1))){var d=m,v;a.sitecount=array_length(d);if(1==array_length(d))for(k in d){a.singleaid=k;v=gs("LastPass detected a password change for user:")+" "+getusernamefromacct(g_sites[k]);break}else v=gs("LastPass detected a password change for domain:")+" "+c;sendCS(b,{cmd:"showchangenotification",text:v,
notificationdata:a});g_persistent_notifications[b]={cmd:"showchangenotification",text:v,notificationdata:a}}}else if(!hasNeverSave(a.url,c)){var d=getsites(c),w;for(w in d)if(check_ident_aid(w)&&"undefined"!=typeof g_sites[w]&&(k=g_sites[w],(!f||e==lpmdec_acct(k.username,!0,k,g_shares)||0==e.indexOf("****"))&&g==lpmdec_acct(k.password,!0,k,g_shares)||k.save_all&&isMatch(k,f,e,g)||e==lpmdec_acct(k.username,!0,k,g_shares)&&""==g))return;g_notification_type="save";g_notification_data=a;"function"==typeof ManSubmitCallback?
(f=[],f.postdata=g_notification_data.formdata,f.tld=c,ManSubmitCallback(f)):(0!=lpGetPref("showSaveSiteNotifications",0)&&sendTS({cmd:"notification",type:"save"}),0!=lpGetPref("showSaveNotificationBar",1)&&lpCheckAddSite(a.username,a.password,c)&&(sendCS(b,{cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),notificationdata:LPJSON.stringify(a)}),g_persistent_notifications[b]={cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),notificationdata:LPJSON.stringify(a)}))}}}}
function lpCheckAddSite(b,a,d){var f=lp_get_gmt_timestamp(),c=[],e;for(e in g_rejectedaddsites){var g=g_rejectedaddsites[e];f>g.rejectedTime+600&&(c[c.length]=e)}for(e=c.length-1;0<=e;e--)g_rejectedaddsites.splice(c[e],1);for(e in g_rejectedaddsites)if(g=g_rejectedaddsites[e],g.username==b&&lpdec(g.encryptedPassword)==a&&compare_tlds(g.tld,d))return!1;return!0}
function handleUpdateFields(b,a){var d=a.aid,f=g_sites[d],c=issharedfolder(g_shares,f.group);if(checkreadonly(c,!0)){var e=[],g=[],j=updateAndEncryptData(a.formdata,e,g,f);update_username_from_fields_if(f,e);for(var k=f.fields.length-1;0<=k;k--)!f.fields[k].otherfield&&"1"!=f.fields[k].otherlogin&&f.fields.splice(k,1);for(k=0;k<e.length;k++)f.fields[f.fields.length]=e[k];g_local_accts_version++;rewritelocalfile();d="data="+en(bin2hex(j))+"&ref="+en(url2hex(a.url))+"&updatefields=1&aid="+en(d);d+=
!1==c?"":"&sharedfolderid="+en(c.id);f.postdata=d;f.posturl=base_url+"gm_deliver.php";f.newvalues=g;updateFieldsFromSubmit(d,f)}}
function handleAddUrid(b,a){var d=a.aid,f=g_sites[d],c=issharedfolder(g_shares,f.group);if(checkreadonly(c,!0)){for(var e=[],g=0;g<f.fields.length;g++)"1"==f.fields[g].otherlogin&&!lp_in_array(f.fields[g].urid,e)&&(e[e.length]=f.fields[g].urid);if(!(10<=e.length)){var j=[],e=[],k=updateAndEncryptData(a.formdata,j,e,f);update_username_from_fields_if(f,j);for(g=0;g<j.length;g++)j[g].otherlogin="1",j[g].url=url2hex(a.url),f.fields[f.fields.length]=j[g];g_local_accts_version++;rewritelocalfile();d="data="+
en(bin2hex(k))+"&ref="+en(url2hex(a.url))+"&addurid=1&aid="+en(d);d+=!1==c?"":"&sharedfolderid="+en(c.id);f.postdata=d;f.posturl=base_url+"gm_deliver.php";f.newvalues=e;updateFieldsFromSubmit(d,f)}}}
function update_username_from_fields_if(b,a){for(var d=0,f="",c=0;c<a.length;c++)if("text"==a[c].type||"email"==a[c].type||"tel"==a[c].type||"url"==a[c].type)if(f=a[c].value,2<=++d)break;if(1==d&&""!=f){for(c=d=0;c<b.fields.length;c++)if(!b.fields[c].otherfield&&("text"==b.fields[c].type||"email"==b.fields[c].type||"tel"==b.fields[c].type||"url"==b.fields[c].type)){d++;break}0==d&&(b.username=f,b.unencryptedUsername=lpdec_acct(crypto_btoa(b.username),b,g_shares))}}
function handleSaveAll(b,a){a.save_all=1;g_site_data=a;openURL(getchromeurl("site.html"))}
function isMatch(b,a,d,f){a=a?!1:!0;for(var c=!1,e=0;e<b.fields.length;e++)if(!("text"!=b.fields[e].type&&"password"!=b.fields[e].type&&"email"!=b.fields[e].type&&"tel"!=b.fields[e].type&&"url"!=b.fields[e].type)){var g=lpmdec_acct(b.fields[e].value,!0,b,g_shares);if(("text"==b.fields[e].type||"email"==b.fields[e].type||"tel"==b.fields[e].type||"url"==b.fields[e].type)&&d==g)a=!0;"password"==b.fields[e].type&&f==g&&(c=!0)}return a&&c?!0:!1}var g_reqindex=0;
function fill(b,a,d,f,c,e,g,j,k,h,p){verbose_log("tabid="+b+"\nacct="+a+"\ndocid="+d+"\nsubmit="+f+"\ndoconfirm="+c+"\ndocnum="+e+"\nallowforce="+g+"\nskip_pwprotect="+j+"\nmanualfill="+k+"\nautomaticallyFill="+h+"\nskip_basicauth="+p);if("undefined"==typeof h||null==h)h=1;k||(k=!1);!j&&(a.pwprotect||g_prompts.login_site_prompt)?(console_log("FILL : Showing Security Prompt"),security_prompt(function(){setTimeout(function(){fill(b,a,d,f,c,e,g,!0,k)},100)})):get_selected_tab(null,function(l){if(!p&&
h&&(g||1==a.basic_auth)&&gettabid(l)==b&&g_ischrome&&have_binary_function("fill_basicauth")){l=getusernamefromacct(a);var r=getpasswordfromacct(a);if(""!=l||""!=r){var m=check_autologin(f,a),s=lp_gettld_url(a.url),u=lp_gettld_url(g_basicauth_origurl);compare_tlds(s,u)&&(s=u);call_binary_function("fill_basicauth",l,r,g?!0:!1,s,m?!0:!1,function(l){l?g_basicauth_found=!1:fill(b,a,d,f,c,e,g,j,k,h,!0)});return}}is_guiless()&&(h=1);l=a.fields;m=l.length;c=1==c?1:0;g=g?1:0;r=null!=a.sharedfromaid&&""!=a.sharedfromaid&&
"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?1:0;if(0!=m){for(m=s=0;m<l.length;m++)"password"==l[m].type&&s++;s=!a.save_all&&0==s;u=[];for(m=0;m<l.length;m++)if(a.save_all||!(1==c&&"password"!=l[m].type&&!g&&!s)){var n=l[m],t=n.value;if(!(""!=n.name&&"undefined"!=typeof u[n.name+t+n.type])){u[n.name+t+n.type]=1;var q=n.type;if(!("undefined"!=typeof a.captcha_id&&""!=a.captcha_id&&a.captcha_id==n.name&&"text"==q)){if("text"==q||"password"==q||"email"==q||"tel"==q||"textarea"==q||"url"==q)t=lpmdec_acct(t,
!0,a,g_shares);if(""!=t){verbose_log("Sending FillRequest: "+m+"\ntype="+q+"\nname="+n.name+"\nvalue=<hidden>");verbose_log("am sending fill request "+n.name);var v="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[a.aid]&&25E3>=(new Date).getTime()-g_last_launch[a.aid];console_log("Sending fillfield reqindex="+g_reqindex);var w={from:"fillfield_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;n={cmd:"fillfield",reqinfo:w,manualfill:k,
name:n.name,value:t,formname:n.formname,type:q,docid:d,aid:a.aid,checked:n.checked,doconfirm:c||a.save_all&&"password"==q?1:2,tabid:b,allowforce:g,custom_js:a.custom_js,sharedsite:r,otherfield:n.otherfield,domains:getacceptabletlds(a.url),automaticallyFill:h,is_launch:v,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)};""!=a.custom_js&&(n.username=getusernamefromacct(a),n.password=getpasswordfromacct(a),n.onlyfill=f?0:1);sendCS(b,n,e)}}}}}else g&&(console_log("no fields. finding best match "+
getusernamefromacct(a)+" and <hidden>"),v="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[a.aid]&&25E3>=(new Date).getTime()-g_last_launch[a.aid],console_log("Sending fillbest from A reqindex="+g_reqindex),w={from:"fillbest_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,sendCS(b,{cmd:"fillbest",reqinfo:w,username:getusernamefromacct(a),password:getpasswordfromacct(a),docid:d,aid:a.aid,custom_js:a.custom_js,updatefields:1,addurid:0,
sharedsite:r,domains:getacceptabletlds(a.url),automaticallyFill:h,is_launch:v,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},e));g&&logLoginAndCheckWeakPassword(b,a);if(1!=c&&(m=check_autologin(f,a),"undefined"!=typeof AUTOSUBMIT&&(m=!0),"string"==typeof a.custom_js&&""!=a.custom_js&&sendCS(b,{cmd:"run_custom_js",docid:d,custom_js:a.custom_js,username:getusernamefromacct(a),password:lpmdec_acct(a.password,!0,a,g_shares),onlyfill:m?0:1,loc:3},e),("string"!=typeof a.custom_js||
-1==a.custom_js.indexOf("lpdontsubmit"))&&m))l="undefined"!=typeof a.submit_id?a.submit_id:"",r="undefined"!=typeof a.submit_html?a.submit_html:"",m="undefined"!=typeof a.submit_js?a.submit_js:"",is_guiless()&&"bankofamerica.com"==lp_gettld_url(a.url)||sendCS(b,{cmd:"submit",docid:d,submit_id:l,submit_html:r,submit_js:m},e)})}
function logLoginAndCheckWeakPassword(b,a){get_all_windows({populate:!0},function(d){for(var f=0;f<d.length;f++)for(var c=0;c<get_tabs_length(d[f]);c++){var e=get_tabs(d[f])[c];if(gettabid(e)==b&&(checkWeakAndDuplicate(a,b,lp_gettld_url(gettaburl(e))),(g_loglogins||LPISLOC)&&"undefined"==typeof g_loggedLogins[a.aid]))g_loggedLogins[a.aid]="1",loglogintab(a.aid,e)}})}function showpageoverlay(b){sendCS(b,{cmd:"showoverlay",urlprefix:getchromeurl("",!0)})}
function check_autologin(b,a){var d=!1;if(b)d=!0;else if(a.autologin){var f=(new Date).getTime(),c=parseInt(lpGetPref("autoautoVal",25));if(isNaN(c)||""==c||0>=c)c=25;c=f-1E3*c;if("undefined"==typeof a.last_auto_login||isNaN(a.last_auto_login)||a.last_auto_login<c)console_log("Launching autologin"),a.last_auto_login=f,d=!0}return d}
function fillfieldsconfirm(b){var a=b.url,d=b.result,f=b.aid,c=b.docid,e=b.tabid,g=b.doconfirm,j=b.manualfill,k="undefined"!=typeof b.automaticallyFill?b.automaticallyFill:1,h=g_sites[f];if("undefined"!=typeof g_sites[f]){if(d&&(logLoginAndCheckWeakPassword(e,h),2==g))return;g=null!=h.sharedfromaid&&""!=h.sharedfromaid&&"0"!=h.sharedfromaid&&"null"!=h.sharedfromaid?1:0;if(h.save_all){if(!d||j)a="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[h.aid]&&25E3>=(new Date).getTime()-
g_last_launch[h.aid],console_log("Sending fillbest from B reqindex="+g_reqindex),d={from:"fillbest_B",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,sendCS(e,{cmd:"fillbest",reqinfo:d,username:getusernamefromacct(h),password:getpasswordfromacct(h),docid:c,aid:h.aid,updatefields:0,addurid:0,sharedsite:g,domains:getacceptabletlds(h.url),automaticallyFill:k,is_launch:a,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},b.docnum)}else if(d)(h=
g_sites[f])&&fill(e,h,c,null,!1,b.docnum,null,!0,null,k),delete g_fillfieldsmatches[a],delete g_fillfieldsmatchescurridx[a];else if(b.allowforce)a="undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[h.aid]&&25E3>=(new Date).getTime()-g_last_launch[h.aid],console_log("Sending fillbest from C reqindex="+g_reqindex),d={from:"fillbest_C",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,sendCS(e,{cmd:"fillbest",reqinfo:d,username:getusernamefromacct(h),
password:getpasswordfromacct(h),docid:c,aid:h.aid,updatefields:0,addurid:1,sharedsite:g,domains:getacceptabletlds(h.url),automaticallyFill:k,is_launch:a,clearfilledfieldsonlogoff:lpGetPref("clearfilledfieldsonlogoff",0)},b.docnum);else{if(h=g_fillfieldsmatches[a]){g=!1;for(d=0;d<h.length;d++){f=h[d].aid;if(g){(h=g_sites[f])&&fill(e,h,c,null,!0,b.docnum,null,!0,null,k);return}d==g_fillfieldsmatchescurridx[a]&&(g_fillfieldsmatchescurridx[a]++,g=!0)}}delete g_fillfieldsmatches[a];delete g_fillfieldsmatchescurridx[a]}}}
function web2plug(b){"2"==b.rsa?(g_local_key=AES.hex2bin(b.key),g_local_key_hex=b.key,g_local_key_hash=SHA256(g_local_key),rsa_userchangedpassword(),b=opendb(),createDataTable(b),b&&!LPISLOC&&b.transaction(function(a){a.executeSql("DELETE FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"accts"],function(){},function(a,b){console_log(b)})}),lpWriteKeyFile()):""!=g_username&&g_username!=b.username?loggedOut(!1,"web2plug"):(g_local_key=AES.hex2bin(b.key),g_local_key_hex=
b.key,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile())}function recover(b,a,d,f){var c=lpParseUri(a);a=c.directory;c=c.file;a=a.replace(/^\/~[^/]*/,"");""!=a&&"/"!=a&&"/sso/"!=a||"recover.php"==c&&GetOTPHash(null,b,d,f)}
function loginfromwebsite(b){if(""!=b.wxusername&&""!=b.keyhex){var a=opendb();createSavedLoginsTable(a);a&&a.transaction(function(c){var d=(new Date).getTime();c.executeSql("UPDATE LastPassSavedLogins2 SET last_login = ? WHERE username = ?",[d,b.wxusername],function(a,c){0==c.rowsAffected&&a.executeSql("INSERT INTO LastPassSavedLogins2 (username, password, last_login) VALUES (?, '', ?)",[b.wxusername,d])},function(a,b){console_log(b)});c.executeSql("SELECT * FROM LastPassSavedLogins2 WHERE username = ? AND password != ''",
[b.wxusername],function(c,d){if(0<d.rows.length){var f=d.rows.item(0).password,e=function(c){var d=get_key_iterations(b.wxusername);make_lp_key_iterations(b.wxusername,c,d,function(c){AES.bin2hex(c)!=b.keyhex&&a.transaction(function(a){a.executeSql("UPDATE LastPassSavedLogins2 SET password = '' WHERE username = ?",[b.wxusername],function(){},function(a,b){console_log(b)})})})};1==d.rows.item(0)["protected"]?unprotect_data(f,!1,e):2==d.rows.item(0)["protected"]&&e(lpdec(f,AES.hex2bin(SHA256(b.wxusername))))}},
function(){})});var d=AES.hex2bin(b.keyhex),f=null!=g_local_key?AES.bin2hex(g_local_key):"";if(!lploggedin||!(g_username==b.wxusername&&f==b.keyhex))lploggedin&&g_username==b.wxusername?(g_local_key=d,g_local_key_hex=b.keyhex,g_local_key_hash=SHA256(g_local_key)):(lploggedin&&""!=g_username&&loggedOut(!1,"differentuser"),""!=b.wxsessid&&(lp_phpsessid=b.wxsessid),g_local_key=d,g_local_key_hex=b.keyhex,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile(),LP.lplogincheck(!0,null,b.wxusername,b.wxhash))}else lploggedin||
LP.lplogincheck(!0)}
function reorderOnURL(b,a,d,f){var c=lpParseUri(a),e=lpcanonizeUrl(a,c),g="string"==typeof c.path?c.path.split("/"):[],j=lp_gettld_url(a),k=[],h;for(h in b)if(check_ident_aid(h)&&(b=g_sites[h],!("undefined"==typeof b||"undefined"==typeof b.url)))if(b.save_all||!d||!(""==b.unencryptedUsername&&""==b.password))if(!f||accthaspassword(b)){var p=lpParseUri(b.url);b.realmmatch=(a==g_basicauth_url||a==g_basicauth_origurl)&&(lpmdec_acct(b.realm_data,!0,b,g_shares)==g_basicauth_realm||g_basicauth_found&&""==
g_basicauth_realm&&1==b.basic_auth);b.servermatch=c.host==p.host;b.portmatch=compare_ports(c,p);b.serverportmatch=b.servermatch&&b.portmatch?1:0;b.usernamematch="undefined"!=typeof g_username_vals[a]&&""!=g_username_vals[a]&&g_username_vals[a]==b.unencryptedUsername;b.urlmatch=lpcanonizeUrl(b.url)==e?!0:!1;var p="string"==typeof p.path?p.path.split("/"):[],l;for(l=0;l<g.length&&l<p.length&&p[l]==g[l];l++);b.pathlevelmatch=l;b.fieldmatchcount=0;k.push(b)}k.sort(lp_aids_sort_func);return k=checkurlrules(g_urlrules,
k,j,"string"==typeof c.path?c.path:"",c.host,g_sites,get_port(c))}
function lp_aids_sort_func(b,a){return b.realmmatch!=a.realmmatch?b.realmmatch?-1:1:b.usernamematch!=a.usernamematch?b.usernamematch?-1:1:b.fav!=a.fav?"1"==b.fav?-1:1:b.urlmatch!=a.urlmatch?b.urlmatch?-1:1:b.serverportmatch&&a.serverportmatch&&b.pathlevelmatch!=a.pathlevelmatch?b.pathlevelmatch>a.pathlevelmatch?-1:1:b.serverportmatch!=a.serverportmatch?b.serverportmatch?-1:1:b.servermatch!=a.servermatch?b.servermatch?-1:1:b.fieldmatchcount!=a.fieldmatchcount?b.fieldmatchcount>a.fieldmatchcount?-1:
1:b.last_touch!=a.last_touch?b.last_touch>a.last_touch?-1:1:b.name!=a.name?b.name<a.name?-1:1:0}function lp_sort_case_insensitive_name(b,a){b=b.name.toLowerCase();a=a.name.toLowerCase();return b<a?-1:1}function launchautologin(b,a){if(check_ident_aid(b)){var d=g_sites[b];d&&(!a&&(d.pwprotect||g_prompts.login_site_prompt)?security_prompt(function(){launchautologin(b,!0)}):(g_last_launch[d.aid]=(new Date).getTime(),openURL(d.url,function(a,b){g_launches[gettabid(a)]=b},d.aid)))}}
function hasNeverShowIcon(b,a){var d=lpcanonizeUrl(b);if(g_neverurls.onlyshowicons&&0<g_neverurls.onlyshowicons.length){for(var f=!1,c=0;g_neverurls.onlyshowicons&&c<g_neverurls.onlyshowicons.length;c++){var e=g_neverurls.onlyshowicons[c];if(e==a||e==d){f=!0;break}}if(!f)return!0}for(c=0;g_neverurls.nevershowicons&&c<g_neverurls.nevershowicons.length;c++)if(e=g_neverurls.nevershowicons[c],e==a||e==d)return!0;return!1};
