function NotebookSelector(k,l,c,u){function q(b,a,d,c,g){var f=document.createElement("div"),e=document.createElement("span"),k=document.createElement("span");f.setAttribute("name",b.toLowerCase());e.innerText=b;f.id=a;f.className="notebook";"biz"==d||"linked"==d?(f.className+=" "+d,f.setAttribute("type",d)):f.setAttribute("type","pers");g&&f.setAttribute("noShare",!0);c&&(k.innerText=" ("+c+")");f.addEventListener("click",function(){h.guid!==this.id&&t(this,!1);n=!0;l.click()});f.addEventListener("mouseover",
function(){r(this)});f.appendChild(e);f.appendChild(k);f.title=b;c&&(f.title+=" ("+c+")");return f}function v(b){var a=document.createElement("div");a.className="stack";var d=document.createElement("div");d.className="stackHeader";d.innerText=b;a.appendChild(d);return m[b]=a}function w(){if(""==k.value){l.className=l.className.replace(/\s*visible/g,"");for(var b=c.querySelectorAll(".notebook.hidden"),a=0;a<b.length;a++)b.item(a).className=b.item(a).className.replace(/\s*hidden/g,"");e=c.querySelectorAll(".notebook");
for(var d=c.querySelectorAll(".stack.collapsed"),a=0;a<d.length;a++)d.item(a).className=d.item(a).className.replace(/\s*collapsed/g,"")}else{l.className+=" visible";b=k.value.toLowerCase();d=c.querySelectorAll(".notebook:not(.hidden):not([name^='"+b+"'])");for(a=0;a<d.length;a++)d.item(a).className+=" hidden";d=c.querySelectorAll(".notebook.hidden[name^='"+b+"']");for(a=0;a<d.length;a++)d.item(a).className=d.item(a).className.replace(/\s*hidden/g,"");d=c.querySelectorAll(".stack:not(.collapsed)");
for(a=0;a<d.length;a++)d.item(a).className+=" collapsed";e=c.querySelectorAll(".notebook[name^='"+b+"']:not(.hidden)");0<e.length&&r(e.item(0))}}function r(b){var a=c.querySelector(".notebook.highlighted");a&&(a.className=a.className.replace(/\s*highlighted/g,""));h.guid!==b.id&&(b.className+=" highlighted",b.scrollIntoViewIfNeeded())}function t(b,a,d){a&&(s=!0);h={};h.name=b.textContent||b.innerText;h.guid=b.id;var e;e=b.getAttribute?b.getAttribute("type"):b.type;h.type=e;var g=c.querySelector(".notebook.selected");
g&&(g.className=g.className.replace(/\s*selected/g,""));g=b;g.getAttribute||(g=c.querySelector(".notebook[id='"+b.id+"']"));g&&(g.className=g.className.replace(/\s*highlighted/g,"")+" selected",d||g.scrollIntoViewIfNeeded());u&&u({name:"selectedNotebook",noShare:b.getAttribute?"true"===b.getAttribute("noShare"):b.noShare,notebookName:h.name,smart:a,type:e})}function p(){c.style.height="";c.style.height=Math.min(x,c.offsetHeight)}var x=224,n=!1,s=!1,e,h,m={};l.addEventListener("click",function(){k.value=
"";w();k.focus()});k.addEventListener("input",w);k.addEventListener("keydown",function(b){if(38==b.keyCode||40==b.keyCode){e||(e=c.querySelectorAll(".notebook"));var a=c.querySelector(".notebook.highlighted");a||(a=c.querySelector(".notebook.selected"));a&&(a=Array.prototype.slice.call(e).indexOf(a),38==b.keyCode&&-1<a-1&&e.item(a-1)?r(e.item(a-1)):40==b.keyCode&&e.item(a+1)&&r(e.item(a+1)),b.preventDefault())}else 13==b.keyCode&&(a=c.querySelector(".notebook.highlighted"))&&(h.guid!==a.id&&t(a,!1),
n=!0,l.click())});this.addNotebookToAll=function(b,a,d,e,g){b=q(b,a,d,e,g);c.appendChild(b);p();return b};this.addNotebookToStack=function(b,a,d,c,e,f){b=q(b,a,d,c,f);m[e].appendChild(b);p();return b};this.addStackIfNeeded=function(b){if(!m[b])return b=v(b),c.appendChild(b),b};this.changedNotebook=function(){return n};this.focusEntry=function(){k.focus()};this.getNotebook=function(b){return c.querySelector(".notebook[id='"+b+"']")};this.getSelected=function(){return h};this.hasNotChangedSmartFiling=
function(){return s&&!n};this.insertNotebook=function(b,a,d,e,g,f){a=q(a,d,e,g,f);c.insertBefore(a,c.children[b]);p();return a};this.insertNotebookIntoStack=function(b,a,d,c,e,f,h){a=q(a,d,c,e,h);m[f].insertBefore(a,m[f].children[b+1]);p();return a};this.insertStackIfNeeded=function(b,a){if(!m[a]){var d=v(a);c.insertBefore(d,c.children[b]);return d}};this.overridable=function(){return!n&&!s};this.reset=function(){s=n=!1;c.innerHTML="";h=e=null;m={}};this.scrollToSelectedNotebook=function(){if(h&&
h.guid){var b=c.querySelector(".notebook[id='"+h.guid+"']");b&&b.scrollIntoViewIfNeeded()}};this.select=t;this.setListHeight=p;Object.preventExtensions(this)}Object.preventExtensions(NotebookSelector);
