function Auth(B,w){function k(){var a={},d;for(d in b){var e=JSON.parse(JSON.stringify(b[d]));a[d]=e}Persistent.set("savedAuthInfo",{userInfo:a,currentUser:c})}function C(){for(var a=0;a<f.length;a++)n(a,{authenticationToken:null,error:"TIMEOUT"});f=[];h=!1}function n(a,d){try{f[a](d)}catch(c){log.warn("Got error running login callback: "+c)}}function x(a){log.warn("failed login: "+a.trace);a=D(a);for(var d=0;d<f.length;d++)n(d,{error:a});f=[];h=!1}function p(a,d){if(h)if(s&&clearTimeout(s),a)if(a.secondFactorRequired){for(var e=
0;e<f.length;e++)n(e,{authenticationToken:a.authenticationToken,secondFactorDeliveryHint:a.secondFactorDeliveryHint,expiration:(new Date).getTime()-a.currentTime+a.expiration});f=[];h=!1}else{if(a.user&&a.user.id)if(r=(new Date).getTime()-a.currentTime,c=a.user.id.toString(),b[c]={},b[c].username=a.user.username,b[c].authenticationToken=a.authenticationToken,b[c].expiration=a.expiration,b[c].premium=a.user.premiumInfo?a.user.premiumInfo.premium:!1,b[c].shardId=a.user.shardId,b[c].fullName=a.user.name||
a.user.username,b[c].email=a.user.email,b[c].quota=a.user.accounting.uploadLimit,b[c].monthEnd=a.user.accounting.uploadLimitEnd,a.user.businessUserInfo)b[c].businessId=a.user.businessUserInfo.businessId,g().client.UserStore.authenticateToBusiness(y,a.authenticationToken);else{k();m.showLoggedInState();for(e=0;e<f.length;e++)n(e,{authenticationToken:a.authenticationToken,username:a.user.username,userId:c,error:!1,premium:a.user.premiumInfo?a.user.premiumInfo.premium:!1,fullName:a.user.name||a.user.username});
f=[];h=!1}}else x(d)}function y(a,d){if(a){b[c]?(b[c].bizAuthenticationToken=a.authenticationToken,b[c].bizExpiration=a.expiration):log.warn("Got business login for unknown user. Discarding.");k();m.showLoggedInState();for(var e=0;e<f.length;e++)n(e,{authenticationToken:b[c].authenticationToken,bizAuthenticationToken:a.authenticationToken,username:b[c].username,userId:c,error:!1,premium:b[c].premium,fullName:b[c].fullName});f=[];h=!1}else x(d)}function D(a){if(!a)return"UNKNOWN";if("number"===typeof a.code)switch(a.code){case 0:return"NETWORK";
case 503:return"HTTP/503"}for(var d=["name","trace"],c=0;c<d.length;c++)if(a[d[c]]){var b=a[d[c]],l=b.match(/errorCode:(\w+)/);if(l)switch(l[1]){case "DATA_REQUIRED":return b.match(/parameter:password/)?"PASSWORD_REQUIRED":b.match(/parameter:username/)?"USERNAME_REQUIRED":"DATA_REQUIRED";case "INVALID_AUTH":return b.match(/parameter:password/)?"INVALID_PASSWORD":b.match(/parameter:username/)?"INVALID_USERNAME":b.match(/parameter:oneTimeCode/)?"INVALID_TWO_STEP_CODE":"INVALID_AUTH";case "PERMISSION_DENIED":return b.match(/parameter:.*tooManyFailures/)||
b.match(/parameter:.*tooManyMessageAttempts/)?"TOO_MANY_FAILURES":b.match(/parameter:.*User.active/)?"ACCOUNT_DEACTIVATED":b.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"PERMISSION_DENIED";case "AUTH_EXPIRED":return b.match(/parameter:password/)?"EXPIRED_PASSWORD":b.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"AUTH_EXPIRED";case "BAD_DATA_FORMAT":return b.match(/parameter:username/)?"INVALID_USERNAME":"INVALID_AUTH";default:return log.warn("Found unhandled error condition: "+
l[1]+b+" while logging in."),"UNKNOWN"}}log.warn("nothing");return"UNKNOWN"}function E(a){if(!a.expiration)return!1;var b=(new Date).getTime(),b=b-r;return b>a.expiration-18E4?!1:!0}function F(a){if(!a.bizExpiration)return!1;var b=(new Date).getTime(),b=b-r;return b>a.bizExpiration-18E4?!1:!0}function t(a){for(;c;)z(a)}function z(a){a||g().client.UserStore.revokeLongSession(function(a,b){b&&log.error("problem revoking auth token: "+b.trace)},b[c].authenticationToken);delete b[c];c="";for(var d in b){c=
d;break}k();r=0;0==Object.keys(b).length&&m.showLoggedOutState()}function A(a){var d=u();if(d.authenticationToken){var e={authenticationToken:d.authenticationToken};d.bizAuthenticationToken?new Date+18E4>d.bizExpiration?g().client.UserStore.authenticateToBusiness(function(d,l){d?(b[c].bizAuthenticationToken=d.authenticationToken,b[c].bizExpiration=d.expiration,k(),e.bizAuthenticationToken=d.authenticationToken,a(e)):l.trace?/PERMISSION_DENIED/.test(l.trace)&&(/parameter:Business/.test(l.trace)||/parameter:Business\.status/.test(l.trace))?
(delete b[c].bizAuthenticationToken,delete b[c].bizExpiration,delete b[c].businessId,k(),a(e)):(log.error("problem refreshing business token: "+l.trace),t(),a(null)):(log.warn("network was down when trying to refresh biz auth token, but still called callback"),a(e))},d.authenticationToken):(e.bizAuthenticationToken=d.bizAuthenticationToken,a(e)):a(e)}else a(null)}function g(){var a;a=w+m.getBootstrapInfo("serviceHost")+"/json";if(v[a])a=v[a];else{var b=new JsonRpc(null,["UserStore.authenticateLongSession",
"UserStore.authenticateToBusiness","UserStore.revokeLongSession","UserStore.completeTwoFactorAuthentication","UserStore.getUser"],null,w,m.getBootstrapInfo("serviceHost"),B);b.initWithUrl(a);a=v[a]=b}return a}function u(a){a||(a=c);return(a=b[a])?a:{}}function q(a){if(/macintosh/i.test(a))a="MacOS";else if(/windows/i.test(a))if(a=a.match(/Windows NT (.+);/))switch(a[1]){case "3.1":a="Windows NT 3.1";break;case "3.5":a="Windows NT 3.5";break;case "3.51":a="Windows NT 3.51";break;case "4.0":a="Windows NT 4.0";
break;case "5.0":a="Windows 2000";break;case "5.01":a="Windows 2000 SP1";break;case "5.1":a="Windows XP";break;case "5.2":a="Windows XP x64";break;case "6.0":a="Windows Vista";break;case "6.1":a="Windows 7";break;case "6.2":a="Windows 8";break;case "6.3":a="Windows 8.1";break;default:a="Windows"}else a="Windows";else a=/linux/i.test(a)?"Linux":"Unknown Operating System";return SAFARI?"Safari ("+a+")":OPERA?"Opera ("+a+")":YANDEX?"Yandex ("+a+")":"Google Chrome ("+a+")"}var m=Browser.extension.getBackgroundPage().extension;
m.getBootstrapInfo("serviceHost");var v={},b={},c=null,r=0,f=[],s=0,h=!1;(function(){var a=Persistent.get("savedAuthInfo");b={};c="";if(a&&a.currentUser&&a.userInfo){c=a.currentUser;for(var d in a.userInfo)try{b[d]=a.userInfo[d]}catch(e){log.warn("Couldn't restore credentials for user "+d)}if(!b[c])for(d in log.warn("No entry for saved user, picking another."),b){currentuser=d;k();break}}else Persistent.set("savedAuthInfo",{})})();this.getAuthTokens=A;this.isAuthenticated=function(a){function d(d,
f){d?(b[c].bizAuthenticationToken=d.authenticationToken,b[c].bizExpiration=d.expiration,k(),e.bizAuthenticationToken=d.authenticationToken,e.bizExpiration=d.expiration,a(e)):f&&f.trace?/PERMISSION_DENIED/.test(f.trace)&&(/parameter:Business/.test(f.trace)||/parameter:Business\.status/.test(f.trace))?(delete e.businessId,delete b[c].businessId,delete b[c].bizAuthenticationToken,delete b[c].bizExpiration,k(),a(e)):(log.error("problem refreshing business auth token: "+f.trace),t(),a(null)):(log.warn("network was down when trying to refresh biz auth token, but still called callback"),
a(e))}var e={},f=u();f.authenticationToken&&E(f)?(e={username:f.username,authenticationToken:f.authenticationToken,userId:c,shardId:f.shardId,premium:f.premium,fullName:f.fullName},f.bizAuthenticationToken?(e.businessId=f.businessId,F(f)?(e.bizAuthenticationToken=f.bizAuthenticationToken,e.bizExpiration=f.bizExpiration,a(e)):g().client.UserStore.authenticateToBusiness(d,f.authenticationToken)):a(e)):a(null)};this.login=function(a,b,c){c&&f.push(c);h||(h=!0,SAFARI?g().client.UserStore.authenticateLongSession(p,
a,b,"en-safari-clipper-xauth-new","1fbffc8cf53bd605",Persistent.get("deviceID"),q(navigator.userAgent),!0):OPERA?g().client.UserStore.authenticateLongSession(p,a,b,"en-opera-clipper-xauth-new","bda9ae45efd276dc",Persistent.get("deviceID"),q(navigator.userAgent),!0):YANDEX?g().client.UserStore.authenticateLongSession(p,a,b,"en-yandex-clipper-xauth-new","6281f15aacf2b24a",Persistent.get("deviceID"),q(navigator.userAgent),!0):g().client.UserStore.authenticateLongSession(p,a,b,"en-chrome-clipper-xauth-new",
"57542b7c39ab82e9",Persistent.get("deviceID"),q(navigator.userAgent),!0),s=setTimeout(C,3E4))};this.logout=z;this.logoutAll=t;this.getCurrentUser=function(){return c};this.getUserInfo=u;this.completeTwoFactorAuthentication=function(a,b,c){c&&f.push(c);h||(h=!0,g().client.UserStore.completeTwoFactorAuthentication(p,a,b,Persistent.get("deviceID"),q(navigator.userAgent)))};this.updateUserStatus=function(){A(function(a){a?g().client.UserStore.getUser(function(a,e){a?(c=a.id.toString(),b[c]&&(b[c].username=
a.username,b[c].premium=a.premiumInfo?a.premiumInfo.premium:!1,b[c].shardId=a.shardId,b[c].fullName=a.name||a.username,b[c].email=a.email,b[c].quota=a.accounting.uploadLimit,b[c].monthEnd=a.accounting.uploadLimitEnd,a.businessUserInfo?(b[c].businessId=a.businessUserInfo.businessId,g().client.UserStore.authenticateToBusiness(y,b[c].authenticationToken)):(delete b[c].businessId,delete b[c].bizAuthenticationToken,delete b[c].bizExpiration),k())):log.error("error when updating user status: "+e.__proto__.name+
JSON.stringify(e))},a.authenticationToken):log.error("no tokens found when trying to update user status")})};Object.preventExtensions(this)}Object.preventExtensions(Auth);
